<?php

namespace Bez\SupportBundle;

use Bez\SupportBundle\DependencyInjection\CompilerPass\TargetEntityResolverPass;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class BezSupportBundle extends Bundle
{
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub
        $container->addCompilerPass(new TargetEntityResolverPass());
    }

}
